language: go
go:
  - 1.11.x

install:
  - go get github.com/codeuniversity/al-master
  - go get github.com/codeuniversity/al-proto
  - go get github.com/stretchr/testify/assert
  - go get google.golang.org/grpc
  - go get github.com/gorilla/websocket
