language: go
go:
  - 1.11.x

services:
  - docker

install:
  - go get

script:
  - GO111MODULE=on make test
  - GO111MODULE=on go build -o $GOPATH/bin/output main/main.go
  - GO111MODULE=on make image
  - if ["$TRAVIS_BRANCH" = "master"] && ["$TRAVIS_PULL_REQUEST" = "false"]; then GO111MODULE=on make pushImage;