language: go
go:
  - 1.11.x

services:
  - docker

env:
  - GO111MODULE=on

# Explanation on GO111MODULE: Go 1.11 introduced Go modules (go.mod) which gives you the possibility to "go get"
# packages with a specific version (normally go get always fetches the most recent one). In Go 1.11 the go module
# behaviour is disabled by default for packages within $GOPATH. -> Because Travis is copying the repo in the $GOPATH
# you have to set the environment variable GO111MODULE=on to force the module behaviour.
script:
  - make test

deploy:
  provider: script
  script: make image docker-push
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

# seems like it's not deploying if tests fail
# added condition because we don't want to push the new image already at pull request but wait until it's merged
