language: go
go:
  - 1.11.x

services:
  - docker

install:
  - GO111MODULE=on go get # does download go.mod dependencies?

# Explanation on GO111MODULE: Go 1.11 introduced Go modules (go.mod) which gives you the possibility to "go get"
# packages with a specific version (normally go get always fetches the most recent one). In Go 1.11 the go module
# behaviour is disabled by default for packages within $GOPATH. -> Because Travis is copying the repo in the $GOPATH
# you have to set the environment variable GO111MODULE=on to force the module behaviour.
script:
  - GO111MODULE=on make test
  - GO111MODULE=on go build -o $GOPATH/bin/main main/main.go
  - GO111MODULE=on make image

deploy:
  provider: script
  script: GO111MODULE=on make docker-push
  on:
    branch: travis-ci